version: '3'

services:
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      AUTH_ADDRESS: auth
      AUTH_SERVICE_SERVICE_HOST: auth
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
